// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvRA--6uDNf3QAkjxdwT0tC96UyJuK6nE',
    appId: '1:624459069061:web:154d004125d4eac358dbec',
    messagingSenderId: '624459069061',
    projectId: 'agriapp-59c85',
    authDomain: 'agriapp-59c85.firebaseapp.com',
    storageBucket: 'agriapp-59c85.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr5hJvRPKlvzFyxVKteg_8MRU-bPHFM-8',
    appId: '1:624459069061:android:22ee2c9081e4496458dbec',
    messagingSenderId: '624459069061',
    projectId: 'agriapp-59c85',
    storageBucket: 'agriapp-59c85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCiVpMHqcIJORckAFCfl1UiX6WHb_xgEM',
    appId: '1:624459069061:ios:70f76fe44d5b2ad958dbec',
    messagingSenderId: '624459069061',
    projectId: 'agriapp-59c85',
    storageBucket: 'agriapp-59c85.appspot.com',
    iosBundleId: 'dk.cachet.appUsageExample',
  );
}
